"""
Case manifest — 33 cases.
"""

CASES = [
    # Success 15
    {
        "case_id": "add_member",
        "doc": {"a": 1},
        "patch": [{"op": "add", "path": "/b", "value": 2}],
        "expected_outcome": "success",
        "expected_fail_index": None,
        "expected_result": {"a": 1, "b": 2},
    },
    {
        "case_id": "replace_null",
        "doc": {"x": None},
        "patch": [{"op": "replace", "path": "/x", "value": "v"}],
        "expected_outcome": "success",
        "expected_fail_index": None,
        "expected_result": {"x": "v"},
    },
    {
        "case_id": "remove_keep_null",
        "doc": {"a": 1, "n": None},
        "patch": [{"op": "remove", "path": "/a"}],
        "expected_outcome": "success",
        "expected_fail_index": None,
        "expected_result": {"n": None},
    },
    {
        "case_id": "array_insert_mid",
        "doc": {"arr": [0, 2, 3]},
        "patch": [{"op": "add", "path": "/arr/1", "value": 1}],
        "expected_outcome": "success",
        "expected_fail_index": None,
        "expected_result": {"arr": [0, 1, 2, 3]},
    },
    {
        "case_id": "array_append_dash",
        "doc": {"arr": [1]},
        "patch": [{"op": "add", "path": "/arr/-", "value": 2}],
        "expected_outcome": "success",
        "expected_fail_index": None,
        "expected_result": {"arr": [1, 2]},
    },
    {
        "case_id": "pointer_slash_escape",
        "doc": {"a/b": 5},
        "patch": [{"op": "replace", "path": "/a~1b", "value": 6}],
        "expected_outcome": "success",
        "expected_fail_index": None,
        "expected_result": {"a/b": 6},
    },
    {
        "case_id": "pointer_tilde_escape",
        "doc": {"a~b": 5},
        "patch": [{"op": "replace", "path": "/a~0b", "value": 6}],
        "expected_outcome": "success",
        "expected_fail_index": None,
        "expected_result": {"a~b": 6},
    },
    {
        "case_id": "root_replace",
        "doc": {"old": 1},
        "patch": [{"op": "replace", "path": "", "value": {"new": 2}}],
        "expected_outcome": "success",
        "expected_fail_index": None,
        "expected_result": {"new": 2},
    },
    {
        "case_id": "copy_deep_isolation",
        "doc": {"src": [1, 2], "dst": None},
        "patch": [{"op": "copy", "from": "/src", "path": "/dst"}],
        "expected_outcome": "success",
        "expected_fail_index": None,
        "expected_result": {"src": [1, 2], "dst": [1, 2]},
        "post_mutate_check": True,
    },
    {
        "case_id": "move_member",
        "doc": {"a": 7, "b": None},
        "patch": [{"op": "move", "from": "/a", "path": "/b"}],
        "expected_outcome": "success",
        "expected_fail_index": None,
        "expected_result": {"b": 7},
    },
    {
        "case_id": "test_pass",
        "doc": {"k": "v"},
        "patch": [{"op": "test", "path": "/k", "value": "v"}, {"op": "replace", "path": "/k", "value": "w"}],
        "expected_outcome": "success",
        "expected_fail_index": None,
        "expected_result": {"k": "w"},
    },
    {
        "case_id": "number_equality_1_1_0",
        "doc": {"n": 1.0},
        "patch": [{"op": "test", "path": "/n", "value": 1}],
        "expected_outcome": "success",
        "expected_fail_index": None,
        "expected_result": {"n": 1.0},
    },
    {
        "case_id": "ignored_extra_member",
        "doc": {"k": 1},
        "patch": [{"op": "replace", "path": "/k", "value": 2, "extra": "ignored"}],
        "expected_outcome": "success",
        "expected_fail_index": None,
        "expected_result": {"k": 2},
    },
    {
        "case_id": "root_add",
        "doc": {"old": 1},
        "patch": [{"op": "add", "path": "", "value": {"new": 3}}],
        "expected_outcome": "success",
        "expected_fail_index": None,
        "expected_result": {"new": 3},
    },
    {
        "case_id": "root_test_pass",
        "doc": {"a": 1},
        "patch": [{"op": "test", "path": "", "value": {"a": 1}}],
        "expected_outcome": "success",
        "expected_fail_index": None,
        "expected_result": {"a": 1},
    },
    # test_failed 2
    {
        "case_id": "test_fail_rollback",
        "doc": {"k": "v"},
        "patch": [{"op": "replace", "path": "/k", "value": "x"}, {"op": "test", "path": "/k", "value": "nope"}],
        "expected_outcome": "test_failed",
        "expected_fail_index": 1,
        "expected_result": None,
    },
    {
        "case_id": "true_not_equal_1",
        "doc": {"k": True},
        "patch": [{"op": "test", "path": "/k", "value": 1}],
        "expected_outcome": "test_failed",
        "expected_fail_index": 0,
        "expected_result": None,
    },
    # array_index_error 2
    {
        "case_id": "dash_reject_replace",
        "doc": {"arr": [1]},
        "patch": [{"op": "replace", "path": "/arr/-", "value": 9}],
        "expected_outcome": "array_index_error",
        "expected_fail_index": 0,
        "expected_result": None,
    },
    {
        "case_id": "array_index_out_of_range",
        "doc": {"arr": [1, 2]},
        "patch": [{"op": "add", "path": "/arr/5", "value": 9}],
        "expected_outcome": "array_index_error",
        "expected_fail_index": 0,
        "expected_result": None,
    },
    # invalid_pointer 1
    {
        "case_id": "invalid_pointer_escape",
        "doc": {"a": 1},
        "patch": [{"op": "replace", "path": "/a~2b", "value": 2}],
        "expected_outcome": "invalid_pointer",
        "expected_fail_index": 0,
        "expected_result": None,
    },
    # source_missing 2
    {
        "case_id": "copy_source_missing",
        "doc": {},
        "patch": [{"op": "copy", "from": "/missing", "path": "/x"}],
        "expected_outcome": "source_missing",
        "expected_fail_index": 0,
        "expected_result": None,
    },
    {
        "case_id": "move_source_missing",
        "doc": {},
        "patch": [{"op": "move", "from": "/missing", "path": "/x"}],
        "expected_outcome": "source_missing",
        "expected_fail_index": 0,
        "expected_result": None,
    },
    # move_into_descendant 1
    {
        "case_id": "move_into_descendant",
        "doc": {"a": {"b": 1}},
        "patch": [{"op": "move", "from": "/a", "path": "/a/b"}],
        "expected_outcome": "move_into_descendant",
        "expected_fail_index": 0,
        "expected_result": None,
    },
    # invalid_operation 5
    {
        "case_id": "unknown_op",
        "doc": {},
        "patch": [{"op": "zap", "path": "/x"}],
        "expected_outcome": "invalid_operation",
        "expected_fail_index": 0,
        "expected_result": None,
    },
    {
        "case_id": "missing_op_member",
        "doc": {},
        "patch": [{"path": "/x", "value": 1}],
        "expected_outcome": "invalid_operation",
        "expected_fail_index": 0,
        "expected_result": None,
    },
    {
        "case_id": "missing_path_member",
        "doc": {},
        "patch": [{"op": "add", "value": 1}],
        "expected_outcome": "invalid_operation",
        "expected_fail_index": 0,
        "expected_result": None,
    },
    {
        "case_id": "op_not_string",
        "doc": {},
        "patch": [{"op": 123, "path": "/x", "value": 1}],
        "expected_outcome": "invalid_operation",
        "expected_fail_index": 0,
        "expected_result": None,
    },
    {
        "case_id": "path_not_string",
        "doc": {},
        "patch": [{"op": "add", "path": 123, "value": 1}],
        "expected_outcome": "invalid_operation",
        "expected_fail_index": 0,
        "expected_result": None,
    },
    # invalid_patch_document 1
    {
        "case_id": "patch_not_array",
        "doc": {},
        "patch": {"op": "add", "path": "/x", "value": 1},
        "expected_outcome": "invalid_patch_document",
        "expected_fail_index": None,
        "expected_result": None,
        "patch_is_input": True,
    },
    # invalid_json 2
    {
        "case_id": "malformed_doc_json",
        "doc_input_raw": "{bad json",
        "doc_input_kind": "malformed",
        "patch": [{"op": "add", "path": "/x", "value": 1}],
        "expected_outcome": "invalid_json",
        "expected_fail_index": None,
        "expected_result": None,
    },
    {
        "case_id": "malformed_patch_json",
        "doc": {},
        "patch_input_raw": '[{"op":',
        "patch_input_kind": "malformed",
        "expected_outcome": "invalid_json",
        "expected_fail_index": None,
        "expected_result": None,
    },
    # target_missing 1
    {
        "case_id": "nonexistent_intermediate",
        "doc": {},
        "patch": [{"op": "add", "path": "/a/b", "value": 1}],
        "expected_outcome": "target_missing",
        "expected_fail_index": 0,
        "expected_result": None,
    },
    # root_removal_unsupported 1
    {
        "case_id": "root_remove_rejected",
        "doc": {"a": 1},
        "patch": [{"op": "remove", "path": ""}],
        "expected_outcome": "root_removal_unsupported",
        "expected_fail_index": 0,
        "expected_result": None,
    },
]
